version: "3"
services:
  server:
    image: app
    ports:
      - "8010:8010"
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/employeemanagement?createDatabaseIfNotExist=true
    networks:
      - springmysql-net
    depends_on:
      - mysqldb

  mysqldb:
    image: mysql:5.7
    networks:
      - springmysql-net
    environment:
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=employeemanagement
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=admin

networks:
  springmysql-net:
